### ISSUE TITLE
PDM mics array question

### ISSUE THREAD

**Issue by xfce** [Lwao/HDL4PDM2PCM#1]
Hi
   Our project want to use a PDM mics array,   128 PDM  mics, then transfer the mics array's data to the system use USB3.0 or eth 1000Mbps, some examples thanks ^-^

**Comment by Lwao** [comment]
That's a nice project.

I think is hard to find an example in such specific matter, but I can draw some ideas with you. First of all I we need to define some specifications, since your project is so robust the details are very important:

- Are all mics the same? Same clock rate? Same SNR and AOP?
- Each mic output a PDM according to its input clock (clock=5MHz, samplerate=5Msps), then the PDM to PCM conversion apply some downsampling rate (or oversampling rate, OSR) to reduce the samplerate. It is commom that the OSR is in base 2  (e.g. 2, 4, 8, 16, etc). Applying the OSR=32 would reduce 5Msps to 156ksps. So you need to specify your application passing band.
- The project that I'm doing in this repo is an interface highly parameterizable that supports many filter configurations, including mutiple OSRs. I don't think that this is useful for your project, since my design has a generalist point of view it is more suitable when you do not know the nature of the audio application (voice? music? ultrasonic?). You have to define your audio application.

Since you are using so many mics you could trim such synthetized hardware to your needs (sample rate, OSR and passing band) to optmize the use of logic arrays. But if you want to implement in a microcontroller framework I suggest research for the STM32 since it has a more suitable peripheral interface with the SAI or DFSDM (check the [playlist](https://youtube.com/playlist?list=PLwqrqfRKpbeIxgnKq1_hTCULCaL7LBHmN)).
